config/routes.rb
QuantifiedLife::Application.routes.draw do
  require 'sidekiq/web'
  constraints Clearance::Constraints::SignedIn.new { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :posts

  resources :photos do
    collection do
      get :batch_upload
      post :multi_create
    end
  end

  resources :days, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :fetch_moves
    end
    collection do
      get :export
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :github, only: [:index] do
    collection do
      get :backfill
    end
  end

  get '/auth/dropbox/callback' => 'callback#dropbox'
  get '/auth/github/callback' => 'callback#github'
  get '/auth/moves/callback' => 'callback#moves'

  root to: "home#index"
  get '/status' => 'home#status'
  get '/photos/image/:id' => 'photos#image', constraints: { id: /.+/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  include ExtraInfoAttributes

  has_many :github_events
  has_many :photos
  has_many :posts
  has_many :days

  def can_view?(user)
    can_edit?(user) || user.permitted_viewers.include?(self.id)
  end

  def can_edit?(user)
    admin? || user == self
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorize
  before_action :check_viewable, only: [:show]
  before_action :check_editable, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
    @attributes = @user.extra_info_attributes.to_json
  end

  def update
    params[:user][:extra_info_attributes] = params[:user][:extra_info_attributes].try(:values)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        @attributes = @user.extra_info_attributes.to_json
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(extra_info_attributes: [:key_name, :type, :value])
  end

  def check_viewable
    unless current_user.can_view?(@user)
      flash[:notice] = 'You are not permitted to view this user'
      redirect_to root_path
    end
  end

  def check_editable
    unless current_user.can_edit?(@user)
      flash[:notice] = 'You are not permitted to edit this user'
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include AuthHelper

  def github_url
    if @user == current_user
      link_to('Link Your Github', github_client.authorize_url(redirect_uri: redirect_uri('github')))
    else
      'No Github Linked'
    end
  end

  def dropbox_url
    if @user == current_user
      link_to('Link Your Dropbox', dropbox_client.start)
    else
      'No Dropbox Linked'
    end
  end

  def moves_url
    link_to('Link Moves',
            moves_client.auth_code.authorize_url(scope: 'activity location',
                                                 redirect_uri: redirect_uri('moves')))
  end
end

app/views/users/edit.html.haml
%h1 Editing User

= form_for(@user, html: { 'ng-controller' => 'UserCtrl' }) do |f|

  = render partial: 'shared/metadata'

  = f.submit 'Save User', class: 'btn'

= link_to 'Show', @user

app/views/users/index.html.haml
%h1 Users

%table.table.table-condensed
  %tr
    %th Email

  - @users.each do |user|
    %tr
      %td
        - if current_user.can_view?(user)
          = link_to user.email, user
        - else
          [Anonymous]

app/views/users/show.html.haml
%p
  %b Email
  = @user.email

%p
  %b Default Metadata:
  = @user.extra_info

%p
  %b Github
  %i.fa.fa-github
  - if @user.github_token
    = link_to "View Github Events", github_index_path(user_id: @user.id)
  - else
    = github_url

%p
  %b Dropbox
  %i.fa.fa-dropbox
  - if @user.dropbox_token
    = link_to "View Photos", photos_path(user_id: @user.id)
  - else
    = dropbox_url

%p
  %b Moves
  %i.fa.fa-location-arrow
  - if @user.moves_token
    = link_to "View Moves", "#"
  - else
    = moves_url

%p
  %b Days
  %i.fa.fa-calendar
  = link_to "View Days", days_path(user_id: @user.id)

%p
  %b Posts
  %i.fa.fa-book
  = link_to "View Posts", posts_path(user_id: @user.id)

%p
  %b Permitted Viewers
  %ul
    - @user.permitted_viewers.each do |viewer|
      %li= User.find(viewer).email

- if current_user.can_edit?(@user)
  = link_to 'Edit', edit_user_path(@user)