config/routes.rb
QuantifiedLife::Application.routes.draw do
  require 'sidekiq/web'
  constraints Clearance::Constraints::SignedIn.new { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :posts

  resources :photos do
    collection do
      get :batch_upload
      post :multi_create
    end
  end

  resources :days, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :fetch_moves
    end
    collection do
      get :export
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :github, only: [:index] do
    collection do
      get :backfill
    end
  end

  get '/auth/dropbox/callback' => 'callback#dropbox'
  get '/auth/github/callback' => 'callback#github'
  get '/auth/moves/callback' => 'callback#moves'

  root to: "home#index"
  get '/status' => 'home#status'
  get '/photos/image/:id' => 'photos#image', constraints: { id: /.+/ }
end

app/models/day.rb
class Day < ActiveRecord::Base
  include ExtraInfoAttributes

  belongs_to :user

  validates :date, presence: true, uniqueness: true

  after_initialize :defaults, unless: :persisted?

  after_create :add_locations
  after_create :async_fetch_data

  def defaults
    self.date ||= Date.yesterday
    self.end_location ||= start_location
    self.extra_info ||= user.try(:extra_info) || {}
    self.headline ||= ''
    self.moves_storyline ||= {}
    self.moves_summary ||= {}
    self.impact ||= 0
  end

  def posts
    Post.where(date: date, user_id: user.id)
  end

  def add_locations
    [start_location, end_location].each do |location|
      if location.present? && !user.locations.include?(location)
        user.locations << location
        user.save
      end
    end
  end

  def self.fetch_moves(day_id)
    Day.find(day_id).fetch_moves
  end

  def fetch_moves
    return unless user.moves_token
    client = Moves::Client.new(user.moves_token)
    self.moves_storyline = client.daily_storyline(date).first
    self.moves_summary = client.daily_summary(date).first
    self.save
  rescue RestClient::BadRequest
  end

  #TODO: As more API's become integrated, have this start up tasks to fetch everything
  def async_fetch_data
    Day.delay.fetch_moves(self.id)
  end

  def moves_places
    return [] unless moves_storyline['segments']
    moves_storyline['segments'].select{ |segment| segment['type'] == 'place' }.
      map{ |segment| segment['place']['name'] }.compact
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :fetch_moves]
  before_action :authorize
  before_action :set_and_check_viewer, only: [:index, :export]
  before_action :check_viewable, only: [:show]
  before_action :check_editable, only: [:edit, :update, :fetch_moves]
  
  impressionist actions: [:show, :index]

  # GET /days
  # GET /days.json
  def index
    @days = Day.where(user_id: @user.id).order('date DESC')
  end

  def export
    # This is for penzu right now. If I need to export for other formats, this
    # should take a parameter and adjust based on that

    @days = Day.where(user_id: @user.id).order('date DESC')

    text = "---------------------\n" +
      "-- Penzu TXT Export\n" +
      "---------------------\n\n" +
      @days.map{ |d| [d.date.to_s, d.date.strftime('%A %B %d, %Y') + ': ' + d.headline, '-------', d.summary]}.join("\n\n")

    send_data(text, filename: 'ql-export.txt')
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @moves_segments = @day.moves_storyline['segments'] || []
    @moves_summary = @day.moves_summary['summary'] || []
  end

  # GET /days/new
  def new
    @day = Day.new(user: current_user, start_location: Day.last.try(:end_location))
    @attributes = @day.extra_info_attributes.to_json
  end

  # GET /days/1/edit
  def edit
    @attributes = @day.extra_info_attributes.to_json
  end

  # POST /days
  # POST /days.json
  def create
    params[:day][:extra_info_attributes] = params[:day][:extra_info_attributes].values
    @day = Day.new(day_params)
    @day.user = current_user

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        @attributes = @day.extra_info_attributes.to_json
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    params[:day][:extra_info_attributes] = params[:day][:extra_info_attributes].values
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        @attributes = @day.extra_info_attributes.to_json
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  def fetch_moves
    @day.fetch_moves
    redirect_to @day
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_day
    @day = Day.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def day_params
    params.require(:day).permit(:date, :headline, :summary, :impact, :start_location, :end_location,
                                extra_info_attributes: [:key_name, :type, :value])
  end

  def check_viewable
    unless current_user.can_view?(@day.user)
      redirect_to root_path
    end
  end

  def check_editable
    unless current_user.can_edit?(@day.user)
      redirect_to root_path
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def impact_class(day)
    case day.impact
    when (8..10) then 'high-impact'
    when (5..7) then 'medium-impact'
    when (2..4) then 'low-impact'
    else ''
    end
  end

  def activity_text(activity)
    "#{activity['activity']}'d #{number_with_delimiter activity['distance']} meters over #{readable_time(activity['duration'])}"
  end

  def readable_time(duration)
    distance_of_time_in_words(Time.at(duration), Time.at(0))
  end
end

app/views/days/_form.html.haml
= form_for(@day, html: { 'ng-controller' => 'DayCtrl' }) do |f|

  .form-group
    = f.label :date
    .input-group
      = f.date_field :date

  .form-group
    = f.label :headline
    .input-group
      = f.text_field :headline, class: 'form-control'
      %span.input-group-addon#day_headline_length #{@day.headline.length}/100

  :javascript
    $('#day_headline').on('keydown', function() {
      $('#day_headline_length').text(this.value.length + "/100");
    });

  .form-group
    = f.label :summary
    = f.text_area :summary, style: 'display: none;'
    #epiceditor

  .row
    .col-lg-4
      .input-group
        .input-group-button
          = f.label :start_location
        = f.text_field :start_location, class: 'ui-widget form-control'
    .col-lg-4
      .input-group
        .input-group-button
          = f.label :end_location
        = f.text_field :end_location, class: 'ui-widget form-control'
    .col-lg-4
      .input-group
        = f.label :impact
        = f.number_field :impact, min: 0, max: 10, class: 'form-control'

  = render partial: 'shared/metadata'

  = f.submit 'Record Day', class: 'btn'

:javascript
  var editor = new EpicEditor({
    textarea: 'day_summary',
    basePath: '/epiceditor'
  }).load();

  $(function() {
    $('#day_start_location, #day_end_location').autocomplete({
      source: #{@day.user.locations.to_json}
    });
  });

app/views/days/_moves_segment.html.haml
%li
  - if moves_segment['type'] == 'place'
    At
    %b= moves_segment['place']['name'] || 'unknown'
  - elsif moves_segment['type'] == 'move'
    Moved
  from #{Time.parse moves_segment['startTime']} to #{Time.parse moves_segment['endTime']}
  %ul
    - (moves_segment['activities'] || []).each do |activity|
      %li= activity_text(activity)

app/views/days/edit.html.haml
%h1 Editing Day

= render 'form'

= link_to 'Show', @day
\|
= link_to 'Back', days_path

app/views/days/index.html.haml
%h1 My Days. All of them.

%table.table.table-condensed
  %tr
    %th Date
    %th Headline
    %th Cities
    %th Impact
    - @user.extra_info.each do |key, _|
      %th= key

  - @days.each do |day|
    %tr{class: impact_class(day)}
      %td{nowrap: true}= link_to day.date, day
      %td= day.headline
      %td #{day.start_location} => #{day.end_location}
      %td= day.impact
      - @user.extra_info.each do |key, _|
        %td= day.extra_info[key]


%br

= link_to 'New Day', new_day_path

app/views/days/new.html.haml
%h1 New Day

= render 'form'

= link_to 'Back', days_path

app/views/days/show.html.haml
%p
  %b Date:
  = @day.date

%p
  %b Headline:
  = @day.headline

%p
  %b Summary:
  = markdown @day.summary

%p
  %b Posts
  %ul
    - @day.posts.each do |post|
      %li= link_to post.title, post

%p
  %b Location
  #{@day.start_location} => #{@day.end_location}

%p
  %b Moves
  %br
  = link_to "Fetch Moves", fetch_moves_day_path(@day)
  %br
  Summary:
  %ul
    - @moves_summary.each do |summary|
      %li= activity_text(summary)
  Places:
  %ul
    - @day.moves_places.each do |place|
      %li
        %b= place
  Storyline:
  %ul= render partial: 'moves_segment', collection: @moves_segments

%p
  %b Impact:
  = @day.impact
%p
  %b Extra Info:
  = @day.extra_info

= link_to 'Edit', edit_day_path(@day)
\|
= link_to 'Back', days_path