config/routes.rb
QuantifiedLife::Application.routes.draw do
  require 'sidekiq/web'
  constraints Clearance::Constraints::SignedIn.new { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :posts

  resources :photos do
    collection do
      get :batch_upload
      post :multi_create
    end
  end

  resources :days, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :fetch_moves
    end
    collection do
      get :export
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :github, only: [:index] do
    collection do
      get :backfill
    end
  end

  get '/auth/dropbox/callback' => 'callback#dropbox'
  get '/auth/github/callback' => 'callback#github'
  get '/auth/moves/callback' => 'callback#moves'

  root to: "home#index"
  get '/status' => 'home#status'
  get '/photos/image/:id' => 'photos#image', constraints: { id: /.+/ }
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, id: "flash_#{name}", class: "alert alert-#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{type: 'button', 'data-toggle' => 'collapse',
      'data-target' => '#bs-example-navbar-collapse-1'}
      %span.sr-only Toggle navigation
      %span.fa.fa-bars
    = link_to "QuantifiedLife", root_path, class: 'navbar-brand'
  .collapse.navbar-collapse{id: 'bs-example-navbar-collapse-1'}
    - if signed_in?
      %ul.nav.navbar-nav
        %li= link_to "My Days", days_path
        %li= link_to "", new_day_path, class: 'fa fa-plus'
        %li= link_to "My Posts", posts_path
        %li= link_to "", new_post_path, class: 'fa fa-plus'
    %ul.nav.navbar-nav.navbar-right
      - if signed_in?
        %li= link_to "All Users", users_path
      %li.dropdown
        - if signed_in?
          %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            = current_user.email
            %b.fa.fa-caret-square-o-down
          %ul.dropdown-menu
            %li= link_to 'View Profile', user_path(current_user)
            %li= link_to 'Edit Profile', edit_user_path(current_user)
            %li= link_to 'Logout', sign_out_path, method: :delete
        - else
          = link_to "Sign In", sign_in_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Quantifiedlife"
    %meta{:content => content_for?(:description) ? yield(:description) : "Quantifiedlife", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main
        = yield
      %footer
    / ! end of #container